# Generated by Django 4.2.27 on 2026-01-31 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatecategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Template Categories'},
        ),
        migrations.RemoveField(
            model_name='templatecategory',
            name='category_type',
        ),
    ]
