# Generated by Django 4.2.27 on 2026-01-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_templates', '0002_alter_templatecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatecategory',
            options={'ordering': ['category_type', 'name'], 'verbose_name_plural': 'Template Categories'},
        ),
        migrations.AddField(
            model_name='templatecategory',
            name='category_type',
            field=models.CharField(choices=[('industry', 'Industry'), ('season', 'Season'), ('style', 'Style')], default='industry', max_length=20),
        ),
    ]
